service: serverless-tm-agotchi

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource:
        - "#{BigHack2020TmAgotchi.Arn}"
  environment:
    TMAGOTCHI_TABLE_NAME: ${self:custom.tmAgotchiTableName}

package:
  excludeDevDependencies: true

functions:
  getTmAgotchi:
    handler: src/handler.getTmAgotchi
    events:
      - http:
          method: get
          path: get-tmagotchi

  updateTmAgotchi:
    handler: handlers/handler.updateTmAgotchi
    events:
      - schedule: cron(0/60 9-17 ? * MON-FRI *) # every hour between 9-6 Mon to Fri

resources:
  Resources:
    BickHack2020TmAgotchi:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tmAgotchiTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  tmAgotchiTableName: tmAgotchiTableName-${self:provider.stage}
  webpack:
    keepOutputDirectory: true
    includeModules:
      forceExclude:
        - aws-sdk
